---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: default
  labels:
    app: wordpress
data: 
  # Database configuration
  WORDPRESS_DB_HOST: "seanshickey-sql-server.database.windows.net"
  WORDPRESS_DB_NAME: "seanshickey"
  WORDPRESS_DB_USER: "sqladmin"
  
  # WordPress configuration
  WORDPRESS_CONFIG_EXTRA: |
    define('WP_HOME', 'https://seanshickey.com');
    define('WP_SITEURL', 'https://seanshickey.com');
    define('FORCE_SSL_ADMIN', true);
    define('WP_CACHE', true);
    define('WP_DEBUG', false);
    define('WP_DEBUG_LOG', false);
    define('SCRIPT_DEBUG', false);